modLoader="javafml"
loaderVersion="[31,)"
license="GPL3"

[[mods]]
modId="configured"
version="0.4.2"
displayName="Configured"
credits="Hatsondogs for creating icons. LizterZapZap for creating mod logo"
authors="MrCrayfish"
description="Creates a simple GUI config for every mod!"
configBackground="minecraft:textures/block/stone.png"
itemIcon="minecraft:book" #Support for Catalogue mod
logoFile="configured.png"
logoBlur=false

[[dependencies.configured]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.configured]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"
